# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [1]:
import numpy

In [2]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [6]:
print(x[:3])
print(x[3:7])
print(x[7:])

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [7]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [8]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 7.26 ms per loop


In [9]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [11]:
Z += 4

In [13]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [15]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [16]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [17]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [18]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [19]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [20]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [22]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [24]:
x = numpy.arange(10)
y = x[:5]

print(x, y)
y[0] = 10
print(x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [25]:
x = numpy.arange(10)
y = x[:5].copy()
print(x, y)
y[0] = 10
print(x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [26]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([  2.61753308,   2.74203045, -12.42180922, ...,  24.49157226,
         9.56802641,  -1.78917036])

## Sorting

In [27]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [28]:
print(x[:10])
print(x[-10:])

[ 0.00113636  0.00117302  0.00210229  0.00267074  0.00279422  0.00328326
  0.00331814  0.00400971  0.00528764  0.00555372]
[ 0.98898195  0.9907694   0.99305087  0.99309622  0.99312883  0.9936878
  0.9974864   0.99805218  0.9998445   0.99985046]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [29]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [30]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [31]:
indices[:10]

array([313, 523, 716, 162, 913, 756, 137,  86, 163, 833], dtype=int64)

In [32]:
random_numbers.min(), random_numbers.max()

(0.00028872047833095049, 0.99949039190230737)

In [33]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(383, 0.99949039190230737)

In [34]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(313, 0.00028872047833095049)

## Exercise

In [35]:
# 0. import numpy
import numpy as np

In [36]:
# 1. sample 1000 elements from normal distribution 
rand_normals = numpy.random.normal(0, 1.5, 1000)

In [50]:
# 2. leave only positive numbers (from previous exercise)
positive_picks = [x for x in rand_normals if x>=0]

In [69]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
negative_picks = [x for x in rand_normals if x<=0]
print('min =', np.min(negative_picks), '\n'
      'max =', np.max(negative_picks), '\n'
      'mean =', np.mean(negative_picks), '\n'
      'var =', np.var(negative_picks))

min = -4.71781619054 
max = -0.00906006260834 
mean = -1.18968100782 
var = 0.818319215816


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
