# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [1]:
import numpy

In [2]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [10]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [15]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [16]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 4.21 ms per loop


In [18]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [20]:
Z += 4

In [21]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [22]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [23]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [24]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [25]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [26]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [27]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [28]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [30]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [31]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [32]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [33]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([  1.60378952,  -7.93554019,  15.08496978, ...,   2.99862046,
        24.8189873 ,  13.97033105])

## Sorting

In [34]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [35]:
print x[:10]
print x[-10:]

[ 0.00031377  0.00162149  0.00201242  0.0030467   0.00414405  0.00843791
  0.00921826  0.01310851  0.01358288  0.01450559]
[ 0.98683193  0.98961884  0.99159947  0.9932376   0.99418917  0.99496273
  0.99562592  0.99586323  0.99629764  0.99897512]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [36]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [37]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [38]:
indices[:10]

array([611, 318, 855, 907, 761, 777, 196, 778, 726, 989])

In [39]:
random_numbers.min(), random_numbers.max()

(0.00074071263724817538, 0.99964115073986259)

In [40]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(264, 0.99964115073986259)

In [41]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(611, 0.00074071263724817538)

## Exercise

In [42]:
# 0. import numpy
import numpy as np

In [56]:
# 1. sample 1000 elements from normal distribution 
norm_rand = np.random.normal(size=1000)

In [57]:
# 2. leave only positive numbers (from previous exercise)
pos_rand = norm_rand[norm_rand > 0]

In [59]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
neg_rand = norm_rand[norm_rand <= 0]
print(np.min(neg_rand))
print(np.max(neg_rand))
print(np.mean(neg_rand))
print(np.var(neg_rand))

-3.97665244951
-0.00299949777613
-0.807472887819
0.396322464313


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
